services:

  # user:
  #   build:
  #     context: ./user-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"
  #   restart: always
  #   depends_on:
  #     - "postgres"
  #   environment:
  #     - NODE_ENV=production

  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 8080:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_watcher

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  postgres-data:


networks:
  rabbitmq_watcher:
    driver: bridge
